### ISSUE TITLE
using the security disabler in an Item Extension method is unexpected

### ISSUE THREAD

**Issue by benmcevoy** [DeloitteDigitalAPAC/Atlas#11]
In one of the item extensions 
public static Item GetFieldValueAsItem(this Item item, string fieldName)

securityDisabler is used.  I would suggest that If someone needs SecurityDisabler they can useit in their own code.

https://github.com/DeloitteDigitalAPAC/Atlas/blob/a411197a8f3eb1d0b52030e95d2a843dff53cb3f/src/DeloitteDigital.Atlas/Extensions/ItemExtensions.cs#L166-L176

**Comment by heikof** [comment]
I agree. The security disabler should not be used anywhere in Atlas. Sitecore discourages its use (a user switcher should be used instead which ensures security is still applied) and as you said, this should be the responsibility of the consuming code which establishes the context.

**Comment by benmcevoy** [comment]
SecurityDisabler is also used in ApplyWorkflowAction, when an item is edited to set workflow state, which I think is OK?

https://github.com/DeloitteDigitalAPAC/Atlas/blob/master/src/DeloitteDigital.Atlas/Multisite/Workflow/ApplyWorkflowAction.cs#L51-L60
