### ISSUE TITLE
Remove the LinkFieldStyle class and its dependcies

### ISSUE THREAD

**Issue by davidnguyen** [DeloitteDigitalAPAC/Atlas#2]
This class poses a very specific concern on a particular solution/implementation context and there fore shouldn't be held at the framework level. The full class name is **DeloitteDigital.Atlas.FieldRendering.LinkFieldStyle**.

**Comment by heikof** [comment]
I agree - this isn't supposed to be part of Atlas. Let's remove it for the next release.

**Comment by davidnguyen** [comment]
@heikof I've created a pull request to remove it, and the dependencies. This change will break any solution that uses the AsButton method from the ILinkFieldRenderingString interface.

https://github.com/DeloitteDigitalAPAC/Atlas/pull/3

**Comment by heikof** [comment]
Thanks David - this is now merged into develop and will be part of the next release for Atlas.
